export enum ORDER_STATUS {
  CREATED = 'CREATED',
  ASSIGNED = 'ASSIGNED',
  PICKED_UP = 'PICKED_UP',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export const ORDER_STATUS_TRANSITIONS: Record<
  ORDER_STATUS,
  ORDER_STATUS[]
> = {
  [ORDER_STATUS.CREATED]: [
    ORDER_STATUS.ASSIGNED,
    ORDER_STATUS.CANCELLED,
  ],

  [ORDER_STATUS.ASSIGNED]: [
    ORDER_STATUS.PICKED_UP,
    ORDER_STATUS.CANCELLED,
  ],

  [ORDER_STATUS.PICKED_UP]: [
    ORDER_STATUS.IN_TRANSIT,
  ],

  [ORDER_STATUS.IN_TRANSIT]: [
    ORDER_STATUS.DELIVERED,
  ],

  [ORDER_STATUS.DELIVERED]: [],

  [ORDER_STATUS.CANCELLED]: [],
};
